dockers:
  - use: buildx
    goarch: amd64
    image_templates:
    - "smark91/{{ .ProjectName }}:{{ .Version }}"
    - "smark91/{{ .ProjectName }}:latest"
  - use: buildx
    goarch: arm64
    image_templates:
    - "smark91/{{ .ProjectName }}:{{ .Version }}"
    - "smark91/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
