dockers:
  - use: buildx
    image_templates:
    - "smark91/{{ .ProjectName }}:{{ .Version }}"
    - "smark91/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64/v8"
