dockers:
  - use: buildx
    goarch: amd64
    image_templates:
    - "smark91/{{ .ProjectName }}:{{ .Version }}-amd64"
    - "smark91/{{ .ProjectName }}:latest-amd64"
    skip_push: false
  - use: buildx
    goarch: arm64
    image_templates:
    - "smark91/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    - "smark91/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    skip_push: false

docker_manifests:
- name_template: "smark91/{{ .ProjectName }}:{{ .Version }}"
  image_templates:
  - "smark91/{{ .ProjectName }}:{{ .Version }}-amd64"
  - "smark91/{{ .ProjectName }}:{{ .Version }}-arm64v8"
- name_template: "smark91/{{ .ProjectName }}:latest"
  image_templates:
  - "smark91/{{ .ProjectName }}:latest-amd64"
  - "smark91/{{ .ProjectName }}:latest-arm64v8"
